  Resources:
    UserseDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: "user_id"
            AttributeType: "S"   
          - AttributeName: "name"
            AttributeType: "S"  
          - AttributeName: "email"
            AttributeType: "S"   
        KeySchema:
          - AttributeName: "user_id"
            KeyType: "HASH"
        GlobalSecondaryIndexes:
          - IndexName: statusAndEndDate
            KeySchema:
              - AttributeName: name
                KeyType: HASH
              - AttributeName: email
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

        
